### ISSUE TITLE
channel_exit_water_sediment~suspended__mass_concentration

### ISSUE THREAD

**Issue by iovereem** [mcflugen/pymt_hydrotrend#1]
Hi Eric, 

I have been tinkering with improving the educational PyMT notebook for Hydrotrend. Sofar this consisted of making the text more clear and comply to te norebook, as opposed to the WMT lab. But I have one question on the core of Hydrotrendpymt. It concerns the suspended load parameter:
channel_exit_water_sediment~suspended__mass_concentration

In the original HT this is calculated per grainsize. I.e. the Cs file (binary or ASCII) consist of arrays of suspended sediment concentrations for each grainsize class. To get to total concentration, one then sums the different size classes. 
Is this how this works in HT PyMT, or do you do that before generating the variable: channel_exit_water_sediment~suspended__mass_concentration? 
Let me know when you can check into this!
Irina

**Comment by mcflugen** [comment]
@iovereem It looks to me like HydroTrend doesn't really calculate concentrations per sediment grain size - just the total sediment concentration. The user specifies in the input file what fractions of each grain size is present in the river,
```
.2 .2 .25 .35	7) Proportion of sediment in each grain size (sum=1)
```
When HydroTrend writes its output files, it just multiplies the total sediment concentration by these fractions to get sediment concentration per grain. At least that's what it looks like to me. Since the user just specifies the fractions, it seems like it doesn't really make sense to add another variable the gives sediment concentration per grain.

I'll continue to dig into a little more. @kettner would probably know the answer to this.

**Comment by iovereem** [comment]
I think you are right on how within Hydrotrend the total SSC is divvied up into the arbitrary number of subclasses (four in your example). 

 I just want to make sure we are not grabbing the first array of the sediment concentrations (i.e. the total CS * 0.2) to set the output variable for the total: channel_exit_water_sediment~suspended__mass_concentration

I'll continue to work on the notebook a little more and send it back to you and the repo once done. 

Irina

**Comment by mcflugen** [comment]
@iovereem No, we're definitely not grabbing just the sediment concentration of the first grain size.

**Comment by iovereem** [comment]
ok excellent! I will close this issue then.
